# Generated by Django 5.2.5 on 2025-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='hearttime_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='hearttime_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
