# Generated by Django 5.2.5 on 2025-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_devicedata_hearttime_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='imei',
            field=models.CharField(max_length=20),
        ),
    ]
