# Generated by Django 5.2.5 on 2025-08-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_devicedata_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='imei',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
