# Generated by Django 5.2.7 on 2025-10-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_devicedata_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='imei',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
