# Generated by Django 5.2.7 on 2025-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_devicedata_imei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedata',
            options={'ordering': ['ranking_id']},
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='id',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='ranking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='imei',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
