# Generated by Django 5.2.7 on 2025-10-04 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_devicedata_options_remove_devicedata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='last_update_detailed_db',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
