# Generated by Django 5.2.7 on 2025-10-04 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_devicedata_last_update_detailed_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='last_update_relative_db',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
